Add author and date
manga-easy/manga_easy_recommendations pull request #1
Opened 2023-05-21 22:50 UTC by cledsonv

2023-06-05 15:58 UTC, BrunoAlm approved these changes
ok

2023-06-05 15:58 UTC, BrunoAlm commented on lib/src/feactures/presenter/ui/atomic/build_title_and_subtitle.dart
> +  final String artistic;
Acho que essa variável ta com nome incorreto.
artistic = artistico
artist = artista

2023-06-05 16:00 UTC, BrunoAlm requested changes
alterar variavel artistic para artist

artistic = artistico
artist = artista

2023-06-05 20:13 UTC, cledsonv commented on lib/src/feactures/presenter/ui/atomic/build_title_and_subtitle.dart
> +  final String artistic;
ta certo, vou resolver isso aqui e mandar de novo

2023-06-05 22:46 UTC, BrunoAlm approved these changes
agora sim tá correto

2023-06-06 02:20 UTC, lucascardo12 approved these changes

2023-06-06 02:20 UTC, merged